# Generated by Django 4.2.27 on 2026-02-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishingplace',
            name='map_embed',
            field=models.TextField(blank=True, help_text='Постави тук целия <iframe> код от Google Maps', null=True, verbose_name='Google Maps Embed Code'),
        ),
    ]
