# Generated by Django 4.2.27 on 2026-02-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing_app', '0002_fishingplace_map_embed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishingplace',
            name='map_embed',
            field=models.TextField(blank=True, null=True, verbose_name='Google Maps Embed Code'),
        ),
        migrations.AlterField(
            model_name='fishingplace',
            name='place_type',
            field=models.CharField(choices=[('river', 'river'), ('lake', 'lake'), ('swamp', 'swamp')], max_length=10, verbose_name='Type of reservoir'),
        ),
    ]
